window.RECIPES = [
  {
    "id": "mercimek-corbasi",
    "title": "Mercimek Çorbası",
    "category": "Çorbalar",
    "time": "30 dk",
    "rating": "4.9",
    "desc": "Sıcacık, pürüzsüz ve tam kıvamında klasik anne usulü mercimek çorbası.",
    "ingredients": ["1 su bardağı kırmızı mercimek","1 adet soğan","1 adet havuç","1 adet patates","1 yemek kaşığı tereyağı","5 su bardağı sıcak su","Tuz, karabiber"],
    "steps": ["Soğanı doğra, havuç ve patatesi küp küp kes.","Tereyağında soğanı hafifçe kavur.","Mercimek, havuç ve patatesi ekle.","Sıcak suyu ekleyip sebzeler yumuşayana kadar pişir.","Blenderdan geçir.","Tuzunu ayarla ve sıcak servis et."],
    "tip": "Limonla servis edersen lezzeti daha da artar.",
    "note": "Bizim evde kış sofralarının vazgeçilmezidir."
  },
  {
    "id": "ezogelin",
    "title": "Ezogelin Çorbası",
    "category": "Çorbalar",
    "time": "40 dk",
    "rating": "4.8",
    "desc": "Mercimek, pirinç ve bulgurun doyurucu buluşması.",
    "ingredients": ["1 su bardağı kırmızı mercimek","2 yemek kaşığı pirinç","2 yemek kaşığı bulgur","1 adet soğan","1 yemek kaşığı domates salçası","6 su bardağı su","Nane, pul biber, tuz"],
    "steps": ["Soğanı tereyağında kavur.","Un ve salçayı ekleyip kısa süre çevir.","Mercimek, pirinç ve bulguru ekle.","Suyu ekleyip kısık ateşte pişir.","Koyulaşınca hafifçe blenderdan geçir.","Nane ve pul biberle servis et."],
    "tip": "Kıvamı koyu olursa biraz sıcak su ekle.",
    "note": "Nane kokusu sofrayı bir anda ev sıcaklığına çevirir."
  },
  {
    "id": "menemen",
    "title": "Menemen",
    "category": "Kahvaltılık",
    "time": "25 dk",
    "rating": "4.9",
    "desc": "Domates, biber ve yumurtayla hızlı ve bol lezzetli kahvaltı klasiği.",
    "ingredients": ["2 yemek kaşığı zeytinyağı","2 adet yeşil biber","2 adet domates","3 adet yumurta","Tuz","Karabiber","İsteğe bağlı beyaz peynir"],
    "steps": ["Biberleri doğrayıp zeytinyağında sotele.","Domatesleri ekleyip yumuşayana kadar pişir.","Tuz ve karabiberi ekle.","Yumurtaları kır ve hafifçe karıştır.","İstersen beyaz peynir ekle.","Sıcak servis et."],
    "tip": "Domates suyunu biraz çekince yumurtayı ekle.",
    "note": "Ekmek banmadan bitirmemek evimizin değişmez kuralıdır."
  },
  {
    "id": "yaprak-sarma",
    "title": "Zeytinyağlı Yaprak Sarma",
    "category": "Ana Yemekler",
    "time": "60 dk",
    "rating": "4.9",
    "desc": "İncecik sarılmış, limon kokulu ve zeytinyağlı klasik sarma.",
    "ingredients": ["2 su bardağı pirinç","2 adet soğan","Yarım çay bardağı zeytinyağı","Dolmalık fıstık","Kuş üzümü","Nane","Tarçın","Dereotu","Asma yaprağı","1 adet limon"],
    "steps": ["Soğanı ince doğra ve zeytinyağında kavur.","Pirinç, fıstık ve kuş üzümünü ekle.","Baharatları ve tuzu kat.","Dereotunu ekleyip iç harcı soğut.","Yapraklara harcı koyup ince ince sar.","Limonlu suyla pişir ve dinlendir."],
    "tip": "Sarmaları çok sıkı sarma; pirinç pişerken pay kalsın.",
    "note": "Bir tabak sarma her zaman kalabalık sofrayı çağrıştırır."
  },
  {
    "id": "pogaca",
    "title": "Anne Poğaçası",
    "category": "Hamur İşleri",
    "time": "45 dk",
    "rating": "4.9",
    "desc": "Yumuşacık hamurlu, peynirli ve mis kokulu ev poğaçası.",
    "ingredients": ["1 su bardağı ılık süt","1 su bardağı ılık su","1 çay bardağı sıvı yağ","1 paket instant maya","1 yemek kaşığı şeker","1 tatlı kaşığı tuz","5 su bardağı un","Beyaz peynir"],
    "steps": ["Süt, su, maya ve şekeri karıştır.","Yağ, tuz ve unu ekleyip yumuşak hamur yoğur.","Hamuru mayalandır.","İç harcı koyup şekillendir.","Üzerine yumurta sarısı sür.","Kızarana kadar pişir."],
    "tip": "Hamur ele hafif yapışan yumuşaklıkta olsun.",
    "note": "Fırından çıktığı an mutfağın kokusu çocukluğu hatırlatır."
  },
  {
    "id": "revani",
    "title": "Revani",
    "category": "Tatlılar",
    "time": "50 dk",
    "rating": "4.8",
    "desc": "İrmikli, şerbetli ve yumuşacık klasik ev tatlısı.",
    "ingredients": ["3 adet yumurta","1 su bardağı şeker","1 su bardağı yoğurt","1 su bardağı irmik","1 su bardağı un","Yarım su bardağı sıvı yağ","1 paket kabartma tozu"],
    "steps": ["Yumurta ve şekeri köpürene kadar çırp.","Yoğurt ve sıvı yağı ekle.","İrmik, un ve kabartma tozunu kat.","Kalıba dök.","Fırında pişir.","Ilıyınca şerbet gezdir."],
    "tip": "Şerbet soğuk, kek ılık olursa kıvamı güzel olur.",
    "note": "Çay saatinin en güvenilir tatlısıdır."
  },
  {
    "id": "sutlac",
    "title": "Sütlaç",
    "category": "Tatlılar",
    "time": "40 dk",
    "rating": "4.8",
    "desc": "Sütlü, hafif ve tarçın kokulu klasik sütlaç.",
    "ingredients": ["1 litre süt","Yarım su bardağı pirinç","1 su bardağı su","1 su bardağı şeker","1 yemek kaşığı nişasta","1 paket vanilin"],
    "steps": ["Pirinci yıka ve suyla haşla.","Sütü ekleyip kaynat.","Şekeri ve vanilini ekle.","Nişastayı suda açıp karışıma ekle.","Kaselere paylaştır.","Soğuk servis et."],
    "tip": "Nişastayı yavaşça ekle, topaklanmasın.",
    "note": "Üzerine biraz tarçın serpilince tamamdır."
  },
  {
    "id": "krep",
    "title": "Krep",
    "category": "Kahvaltılık",
    "time": "20 dk",
    "rating": "4.9",
    "desc": "İncecik, yumuşak ve meyvelerle servis edilen kahvaltılık krep.",
    "ingredients": ["2 adet yumurta","1 su bardağı süt","1 su bardağı un","1 yemek kaşığı eritilmiş tereyağı","1 yemek kaşığı şeker","1 çimdik tuz"],
    "steps": ["Yumurta ve sütü çırp.","Un, şeker ve tuzu ekle.","Eritilmiş tereyağını kat.","Hamuru 10 dakika dinlendir.","İnce bir kat tavaya dök.","İki tarafını da pişir."],
    "tip": "Tava iyice ısınmış olsun.",
    "note": "Meyve ve çikolatayla çocukların favorisi."
  },
  {
    "id": "firin-makarna",
    "title": "Fırın Makarna",
    "category": "Ana Yemekler",
    "time": "50 dk",
    "rating": "4.7",
    "desc": "Beşamel sos ve kaşarla fırında kızarmış doyurucu makarna.",
    "ingredients": ["1 paket makarna","2 yemek kaşığı tereyağı","2 yemek kaşığı un","3 su bardağı süt","1 su bardağı rendelenmiş kaşar","Tuz","Karabiber"],
    "steps": ["Makarnayı haşla ve süz.","Tereyağı ve unla beşamel hazırla.","Sütü ekleyip kıvam aldır.","Makarnayı sosla karıştır.","Kaşar serpip fırın kabına al.","Üstü kızarana kadar pişir."],
    "tip": "Makarnayı çok fazla haşlama, diri kalsın.",
    "note": "Kalabalık sofralar için kurtarıcıdır."
  },
  {
    "id": "imam-bayildi",
    "title": "İmam Bayıldı",
    "category": "Ana Yemekler",
    "time": "60 dk",
    "rating": "4.8",
    "desc": "Zeytinyağlı, bol soğanlı ve domatesli patlıcan klasiği.",
    "ingredients": ["4 adet patlıcan","2 adet soğan","3 adet domates","6 diş sarımsak","Yarım çay bardağı zeytinyağı","Tuz","Şeker","Maydanoz"],
    "steps": ["Patlıcanları alacalı soyup yumuşat.","Soğan ve sarımsağı kavur.","Domates, tuz ve şekeri ekle.","Patlıcanları doldur.","Tencereye dizip biraz su ekle.","Kısık ateşte pişirip soğut."],
    "tip": "Dinlenince lezzeti daha da oturur.",
    "note": "Zeytinyağlı yemekler ertesi gün ayrı güzel olur."
  }
];