"""Included by build_seo.py: useful tools, menus and curated landing pages."""
pantry=['Patates','Yumurta','Yoğurt','Süt','Un','Pirinç','Bulgur','Mercimek','Nohut','Kuru fasulye','Tavuk','Kıyma','Domates','Biber','Soğan','Sarımsak','Kabak','Patlıcan','Havuç','Salatalık','Peynir','Yufka','İrmik','Bisküvi','Şeker','Tereyağı','Zeytinyağı','Salça']
article('mutfakta-ne-var.html','Evdeki Malzemelerle Ne Pişirsem?','Dolabındaki malzemeleri seç, uygun tarifleri ve kontrol etmen gereken eksikleri birlikte gör.','<form id="pantryForm"><fieldset class="pantry-fieldset"><legend>Evde hangi malzemeler var?</legend><div class="pantry-options">'+''.join(f'<label class="pantry-chip"><input type="checkbox" name="pantry" value="{esc(x)}"><span>{esc(x)}</span></label>' for x in pantry)+'</div></fieldset><div class="tool-filters"><label for="pantryTime">Toplam süre</label><select id="pantryTime"><option value="">Sınır yok</option><option value="30">30 dakika ve altı</option><option value="60">60 dakika ve altı</option></select><label><input id="pantryStrict" type="checkbox"> Seçilebilir ana malzemeleri tamam olanlar</label><button id="pantryReset" class="btn" type="button">Seçimi temizle</button></div></form><p id="pantryStatus" role="status"></p><div id="pantryResults" class="pantry-grid"></div><noscript><p>Malzeme seçimi için JavaScript açık olmalıdır. <a href="kategori.html">Tarif arşivini doğrudan inceleyebilirsin.</a></p></noscript><h2>Sonuçlar nasıl seçiliyor?</h2><p>Seçtiğin malzemeler tarif listesindeki ana malzemelerle karşılaştırılır. En çok eşleşen tarifler önce görünür. Bir malzemenin seçili olması, evde tarif için yeterli miktar bulunduğu anlamına gelmez. Su, tuz, baharatlar ve seçeneklerde olmayan malzemeler dahil tam listeyi tarif sayfasında kontrol et.</p><h2>Yemek seçtikten sonra</h2><p>Tarif sayfasında miktarı ayarlayabilir, malzemeleri alışveriş listene ekleyebilir veya pişirme modunda adımları tek tek izleyebilirsin. <a href="menuler.html">Hazır menüler</a> ve <a href="koleksiyonlar.html">tarif koleksiyonları</a> da sofranı planlamana yardımcı olur.</p>')
menus=[
 ('Pazartesi · Bakliyat sofrası',['mercimek-corbasi','kuru-fasulye','pirinc-pilavi'],'Fasulyenin ıslatma süresini bir önceki akşam planla. Ana yemek pişerken çorbayı hazırla; pilavı servise yakın başlat.'),
 ('Salı · Tavuklu akşam',['tavuk-sote','firinda-sutlu-patates','cacik'],'Önce patatesi fırına ver. Tavuk soteyi fırın çalışırken pişir; cacığı servise yakın karıştır.'),
 ('Çarşamba · Sebze ağırlıklı',['yayla-corbasi','imam-bayildi','pirinc-pilavi'],'Patlıcanın ön hazırlığını önce tamamla. Çorbanın terbiyesini kaynar suyla azar azar ılıt ve tarifteki sırayı izle.'),
 ('Perşembe · Nohut günü',['tarhana-corbasi','nohut-yemegi','cacik'],'Nohudu akşamdan ıslat. Ana yemek yumuşadıktan sonra kısa sürede hazırlanan çorba ve cacığı tamamla.'),
 ('Cuma · Fırın sofrası',['ezogelin','firinda-kofte-patates','havuc-tarator'],'Önce köfte ve patatesi tepsiye yerleştir. Fırında pişerken çorbayı ve havuç taratoru hazırla.'),
 ('Cumartesi · Çay saati',['patatesli-borek','kisir','mozaik-pasta'],'Mozaik pastayı en az dört saat önceden hazırla. Kısırı dinlendir; böreği servise yakın fırından çıkar.'),
 ('Pazar · Kahvaltı sofrası',['menemen','pankek','pogaca'],'Poğaçanın mayalanmasını önceden planla. Pankek ve menemeni sofraya oturmadan hemen önce hazırla.')]
menu_html='<p class="content-note">Günler öneridir; menüler her hafta rastgele değişmez. Her tarifin özgün miktarı farklı olabilir. Eklediğin tarifin sayfasında miktarı ayarlayıp menüyü tekrar listeye ekleyebilirsin.</p><div class="menu-grid">'
for title,ids,note in menus:
    selected=[next(r for r in recipes if r['id']==id) for id in ids]
    menu_html+='<section class="menu-card"><p class="kicker">Sofra planı</p><h2>'+esc(title)+'</h2><ul>'+''.join(f'<li><a href="{rurl(r)}">{esc(r["title"])}</a><span>{esc(r["time"])} · {esc(r["servings"])}</span></li>' for r in selected)+'</ul><p>'+esc(note)+'</p><div class="actions"><button class="btn primary" type="button" data-menu-shopping="'+','.join(ids)+'">Alışverişe Ekle</button><button class="btn" type="button" data-menu-favorites="'+','.join(ids)+'">Defterime Ekle</button></div></section>'
menu_html+='</div><p><a href="alisveris-listem.html">Alışveriş listemi aç →</a></p>'
article('menuler.html','Bugün Ne Pişirsem? 7 Günlük Yemek Menüsü','Bakliyat, tavuk, sebze ve çay saati için yedi hazır menü. Tarifleri tek dokunuşla defterine veya alışveriş listene ekle.',menu_html)
article('alisveris-listem.html','Alışveriş Listem','Tariflerden eklediğin malzemeleri bir araya getir, evde bulunanları işaretle ve listeyi indir.','<p id="shoppingStatus" role="status"></p><div id="shoppingRecipes"></div><div class="actions"><button id="shoppingCopy" class="btn" type="button">Listeyi Kopyala</button><button id="shoppingDownload" class="btn primary" type="button">Listeyi İndir</button><button id="shoppingClear" class="btn" type="button">Listeyi Boşalt</button></div><div id="shoppingList"></div><h2>Malzemeler nasıl birleştiriliyor?</h2><p>Aynı isimle ve aynı birimle yazılmış sayısal miktarlar toplanır. Farklı birimler dönüştürülmez; miktar aralıkları, belirsiz ölçüler ve isteğe bağlı malzemeler ayrıca gösterilir. Tariflerdeki özgün açıklamaları kontrol et. Sos, süsleme veya kızartma için ayrılan miktarlar tek bir genel sayıya dönüştürülmez.</p><h2>Liste nerede saklanıyor?</h2><p>Seçtiğin tarifler ve miktarlar bu tarayıcıda saklanır. Evde bulunanları işaretleme geçicidir; sayfayı yenileyince işaretler temizlenir. “Listeyi İndir” düğmesi telefonda saklayabileceğin bir metin dosyası oluşturur.</p>')
# A personal list should not be indexed; keep the public explanation accessible.
shopping=ROOT/'alisveris-listem.html';shopping.write_text(shopping.read_text().replace('index,follow,max-image-preview:large','noindex,follow'));pages.remove('alisveris-listem.html')
collections=[
 ('30-dakikada-yemekler','30 Dakikada Hazırlanan Tarifler',['mercimek-corbasi','menemen','krep','patates-salatasi','pirinc-pilavi','havuc-tarator','tarhana-corbasi','kisir','pankek','cacik'],'Az vakitte sofra kurmak için toplam belirtilen süresi 30 dakika veya daha kısa olan tarifler.','Bu listede ıslatma veya uzun soğutma gerektiren tarifler bulunmaz. Süreler yaklaşık değerlerdir; malzemeleri önceden hazırlamak işini kolaylaştırır. Ana yemek arıyorsan menemen, tamamlayıcı arıyorsan çorba, pilav veya cacık seçebilirsin.'),
 ('kahvalti-tarifleri','Pratik Kahvaltı Tarifleri',['menemen','krep','pankek','pogaca'],'Yumurta, süt ve unla hazırlanabilen sıcak kahvaltı fikirleri.','Hafta içi kısa süre için menemen veya krep; daha uzun bir pazar sofrası için poğaça seçebilirsin. Poğaçanın mayalanma süresi toplam süreye dahildir. Tatlı ve tuzlu seçenekleri birleştirirken tariflerin verdiği adetleri de kontrol et.'),
 ('cay-saati-tarifleri','Çay Saati İçin Tarifler',['pogaca','elmali-kurabiye','patatesli-borek','kisir','mozaik-pasta','revani'],'Börek, kurabiye, salata ve tatlılarla çay sofrası kur.','Tatlılardan dinlenme gerektirenleri önce hazırlamak, fırında pişecek tarifleri sıraya koymak işleri kolaylaştırır. Mozaik pastanın dört saatlik soğutmasını unutma. Bir tuzlu, bir salata ve bir tatlı seçerek kalabalık olmadan dengeli bir ikram sofrası oluşturabilirsin.'),
 ('bakliyat-yemekleri','Bakliyatlı Ev Yemekleri',['kuru-fasulye','nohut-yemegi','mercimek-corbasi','ezogelin'],'Kuru fasulye, nohut ve mercimekle ev usulü sofra fikirleri.','Fasulye ve nohutun ıslatma süresini yemek gününden önce planla. Pişirme zamanı bakliyatın cinsine ve tazeliğine göre değişebilir. Çorba tariflerini aynı malzeme ailesinden daha kısa süren bir alternatif olarak değerlendirebilirsin.'),
 ('firin-yemekleri','Fırında Pişen Yemekler',['firin-makarna','firinda-kofte-patates','firinda-sutlu-patates','patatesli-borek','pogaca','elmali-kurabiye'],'Tepsi yemekleri, börekler ve hamur işleri için fırın tarifleri.','Fırını tarifte yazan sıcaklığa getir. Tepsinin boyutu ve yemeğin kalınlığı pişme süresini etkiler. Porsiyonu artırırken daha büyük tepsi veya iki ayrı tepsi gerekebilir; süreyi miktarla aynı oranda artırmak yerine tarifteki pişme belirtilerini izle.'),
 ('patatesli-tarifler','Patatesle Ne Yapılır?',['patates-salatasi','patatesli-borek','firinda-kofte-patates','firinda-sutlu-patates','mercimek-corbasi'],'Patatesi salatada, börekte, çorbada veya fırın yemeğinde değerlendir.','Patatesin rolü tarife göre değişir: salatada ana malzeme, çorbada kıvam veren yardımcı, köftenin yanında ise tamamlayıcıdır. Dilimleri eşit kesmek fırında daha eşit pişmesini sağlar. Evdeki diğer malzemeleri seçerek uygun olanı malzeme aracında da bulabilirsin.'),
 ('yogurtlu-tarifler','Yoğurtla Yapılan Tarifler',['cacik','yayla-corbasi','havuc-tarator','elmali-kurabiye','revani'],'Yoğurtla serin bir meze, sıcak çorba veya yumuşak hamur hazırla.','Yoğurt yalnızca soğuk mezelere değil, hamur ve çorbaya da girer. Yayla çorbasında terbiyeyi ılıtma adımını atlama. Cacığın su miktarını istediğin kıvama göre ayarlarken tarifteki aralığı kullan. Hamur işlerinde yoğurdun kıvamı un ihtiyacını etkileyebilir.'),
 ('firinsiz-tatlilar','Fırınsız Tatlı Tarifleri',['mozaik-pasta','irmik-helvasi','revani'],'Fırın kullanmadan yapılabilen tatlıları seçmek için tarifleri karşılaştır.','Mozaik pasta fırın gerektirmez ama soğutma ister; irmik helvası ocakta hazırlanır. Revani fırında pişer ve bu koleksiyona dahil değildir. Zamanın azsa hazırlık süresi kadar dinlenme süresini de düşün; servis anını buna göre planla.')]
# Keep every collection's promise consistent with its recipes.
collections[-1]=(collections[-1][0],collections[-1][1],['mozaik-pasta','irmik-helvasi'],collections[-1][3],collections[-1][4].replace(' Revani fırında pişer ve bu koleksiyona dahil değildir.',''))
links=[]
for key,title,ids,desc,intro in collections:
    group=[next(r for r in recipes if r['id']==id) for id in ids];path='koleksiyon-'+key+'.html'
    body='<h2>Hangi tarifi seçmeli?</h2><p>'+esc(intro)+'</p><div class="recipe-grid">'+''.join(card(r) for r in group)+'</div><h2>Tarifi sofrana göre ayarla</h2><p>Tarif sayfasındaki miktar düğmeleriyle malzemeleri ayarla. Pişirmeye başlamadan önce tam malzeme listesini oku; eksikleri alışveriş listene ekle. <a href="mutfakta-ne-var.html">Evdeki malzemelerle tarif bul</a> veya <a href="menuler.html">hazır menülere göz at</a>.</p><p><a href="koleksiyonlar.html">Tüm koleksiyonlar →</a></p>'
    article(path,title,desc,body)
    p=ROOT/path;doc=p.read_text();doc=doc.replace('</head>',structured({'@context':'https://schema.org','@type':'ItemList','name':title,'itemListElement':[{'@type':'ListItem','position':i+1,'url':BASE+rurl(r)} for i,r in enumerate(group)]})+'</head>');p.write_text(doc)
    links.append('<a href="'+path+'"><h2>'+esc(title)+'</h2><p>'+esc(desc)+'</p><small>'+str(len(group))+' tarif</small></a>')
article('koleksiyonlar.html','İhtiyacına Göre Tarif Koleksiyonları','Kısa sürede yemek, kahvaltı, çay saati ve evdeki ana malzemene göre düzenlenmiş tarif listeleri.','<div class="guide-links">'+''.join(links)+'</div>')
# Link the tools from the homepage, notebook, and existing guide hub.
home=ROOT/'index.html';doc=home.read_text();doc=re.sub(r'<section class="section kitchen-discovery">.*?</section>','',doc,flags=re.S)
doc=doc.replace('</main>','<section class="section kitchen-discovery"><div class="container"><div class="section-head"><div><p class="kicker">Sofranı birlikte hazırlayalım</p><h2>Bugün ne pişirsem?</h2></div></div><div class="kitchen-tiles"><a href="mutfakta-ne-var.html"><span>01 · Dolabımdan</span><h3>Evde ne varsa</h3><p>Malzemelerini seç, uygun tarifleri bul.</p></a><a href="menuler.html"><span>02 · Soframa</span><h3>Menüm hazır</h3><p>Yedi günlük yemek ve çay saati fikirleri.</p></a><a href="koleksiyonlar.html"><span>03 · Defterimden</span><h3>Birlikte güzel</h3><p>Vaktine ve ana malzemene göre tarifler.</p></a></div></div></section></main>');home.write_text(doc)
notebook=ROOT/'defterim.html';doc=notebook.read_text()
if 'data-shopping-favorites' not in doc:doc=doc.replace('<div class="actions">','<div class="actions"><button class="btn" type="button" data-shopping-favorites>Alışverişe Ekle</button><a class="btn" href="alisveris-listem.html">Alışveriş Listem</a>',1)
notebook.write_text(doc)
guide=ROOT/'rehberler.html';doc=guide.read_text().replace('<div class="guide-links">','<div class="guide-links"><a href="mutfakta-ne-var.html"><h2>Evde ne varsa</h2><p>Malzemelerini seç ve tarif bul.</p></a><a href="menuler.html"><h2>Yedi günlük menü</h2><p>Tarifleri defterine ve alışveriş listene ekle.</p></a><a href="koleksiyonlar.html"><h2>Tarif koleksiyonları</h2><p>Vaktine ve malzemene göre seç.</p></a>');guide.write_text(doc)
privacy=ROOT/'gizlilik.html';doc=privacy.read_text().replace('<h2>Verileri kaldırma</h2>','<h2>Yeni mutfak araçları</h2><p>Alışveriş tarifleri ams_shopping_v1, seçilen miktarlar ams_portions_v1 anahtarlarıyla bu tarayıcıda saklanır. Malzeme araması yerel olarak yapılır. Pişirme modu destekleyen cihazlarda ekranı açık tutma özelliğini kullanır.</p><h2>Verileri kaldırma</h2>');privacy.write_text(doc)
